codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 50%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "setup.py"
  - "**/__init__.py"