name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: lint/style-and-typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          options: "-S -C --check --diff"
      - name: Spell Check
        uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/typos.toml
