name: Lint

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: lint/style-and-typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      
      - name: Black Formatting Check
        uses: psf/black@stable
        with:
          options: "-S -C --check --diff"
      
      - name: Flake8 Lint Check
        run: |
          flake8 gdplib/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 gdplib/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
      
      - name: Spell Check
        uses: crate-ci/typos@master
        with:
          config: ./.github/workflows/typos.toml
